<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-4R2OF2PC" failures="1" tests="4" name="testscript.ListnerDemo" time="3.138" errors="0" timestamp="2024-05-31T15:31:08 IST" skipped="3">
  <testcase classname="testscript.ListnerDemo" name="demo" time="0.657">
    <skipped/>
    <system-out>
      <![CDATA[demo TestScript has Successfully Started
demo TestScript has Successfully Skipped]]>
    </system-out>
  </testcase> <!-- demo -->
  <testcase classname="testscript.ListnerDemo" name="demo" time="1.108">
    <skipped/>
    <system-out>
      <![CDATA[demo TestScript has Successfully Started
demo TestScript has Successfully Skipped]]>
    </system-out>
  </testcase> <!-- demo -->
  <testcase classname="testscript.ListnerDemo" name="demo" time="0.706">
    <skipped/>
    <system-out>
      <![CDATA[demo TestScript has Successfully Started
demo TestScript has Successfully Skipped]]>
    </system-out>
  </testcase> <!-- demo -->
  <testcase classname="testscript.ListnerDemo" name="demo" time="0.667">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testscript.ListnerDemo.demo(ListnerDemo.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[demo TestScript has Successfully Started
demo has Successfully captured SS]]>
    </system-out>
  </testcase> <!-- demo -->
  <system-out>
    <![CDATA[ListnerSuite has Successfully Executed
Browser opened Successfully
Login Successfully
demo TestScript has Successfully Started
demo TestScript has Successfully Skipped
Logout Successfully
Login Successfully
demo TestScript has Successfully Started
demo TestScript has Successfully Skipped
Logout Successfully
Login Successfully
demo TestScript has Successfully Started
demo TestScript has Successfully Skipped
Logout Successfully
Login Successfully
demo TestScript has Successfully Started
demo has Successfully captured SS
Logout Successfully
Browser Closed Successfully]]>
  </system-out>
</testsuite> <!-- testscript.ListnerDemo -->
